Repository labs12-project-showcase/labs12-project-showcase-FE, pull requests merged in 2019-05, with the labels that each got.

#41 Lowell
  src/components/TopBar.js
  src/components/student/dashboard/StudentDashboard.js
  src/styles/_top-bar.scss
Labels: bug, enhancement

#46 Jake
  src/App.scss
  src/auth/authActions.js
  src/components/TopBar.js
  src/components/home/Cards.js
  src/components/student/profile/StudentProfile.js
  src/components/student/profile/_studentProfile.scss
  src/components/student/profile/studentProfileActions.js
  src/components/student/profile/studentProfileReducer.js
  src/config/Routes.js
  src/config/rootReducer.js
Labels: enhancement

#48 Profile page conditional rendering
  src/components/student/profile/StudentProfile.js
Labels: enhancement

#49 Create profile button redirects to the correct profile page location
  src/components/student/profile/StudentProfile.js
  src/components/student/profileqs/ProfileqsFormSchema.js
  src/components/student/profileqs/profileqsActions.js
Labels: bug, enhancement

#56 Hopefully fix the top bar's "are you logged in" functionality for good
  src/components/TopBar.js
  src/components/student/profile/StudentProfile.js
  src/components/student/share/Share.js
  src/components/student/skills/Skills.js
  src/components/student/status/Status.js
Labels: bug

#57 Hotfix for the subheader
  src/components/TopBar.js
Labels: bug

#67 Fix login.
  src/App.js
  src/auth/authActions.js
  src/auth/axiosAuth.js
Labels: bug

#90 Solve this dumb devtools break our app for anyone that isn't us that …
  src/index.js
Labels: bug

#93 Home page search
  src/components/home/Home.js
  src/components/home/homeActions.js
  src/components/home/homeReducer.js
  src/config/urls.js
Labels: enhancement

#98 Add location filtering
  src/components/home/Home.js
  src/components/home/homeActions.js
Labels: enhancement

#104 Home filtered search tweaks
  src/components/home/Home.js
  src/components/home/homeActions.js
Labels: bug

#114 Admin login route
  src/auth/AdminLogin.js
  src/config/Routes.js
Labels: enhancement

#115 Conditionally render endorsements
  src/components/student/profile/StudentProfile.js
Labels: bug

#118 Admin subnav bar
  src/components/TopBar.js
  src/components/admin/projectTable/ProjectTable.js
  src/components/admin/studentTable/StudentTable.js
Labels: enhancement

#122 Change endorsed to approved.
  src/components/student/profile/StudentProfile.js
Labels: bug

#144 Student delete own profile
  src/auth/Auth.js
  src/auth/authActions.js
  src/components/TopBar.js
  src/components/student/profile/DeleteModal.js
  src/components/student/profile/StudentProfile.js
  src/components/student/profile/studentProfileActions.js
  src/config/Routes.js
Labels: bug, enhancement

#151 Removes the rand() function from the <DeleteModal />
  src/components/student/profile/DeleteModal.js
Labels: bug

#154 Move the delete your account button from the top bar to the edit profile page
  src/components/TopBar.js
  src/components/student/profile/DeleteModal.js
  src/components/student/profile/studentProfileActions.js
  src/components/student/profileqs/Profileqs.js
Labels: bug

#158 Logout before deleting the user to fix the main 'this does not work' …
  src/components/student/profile/studentProfileActions.js
Labels: bug

#160 Add 404 route and redirect to 404 when we try to render a profile fro…
  src/components/student/profile/StudentProfile.js
  src/components/student/profile/studentProfileReducer.js
  src/config/Routes.js
Labels: enhancement

#170 If login returns 200, user already existed, redirect to profile. If l…
  src/auth/authActions.js
Labels: bug

#174 Add a link to the discover page to the top bar.
  src/components/TopBar.js
  src/styles/_top-bar.scss
Labels: enhancement

#184 Fix account deletion, auto-redirect admin login
  src/auth/AdminLogin.js
  src/components/student/profile/studentProfileActions.js
  src/components/utils/Loading.js
  src/config/Routes.js
Labels: bug, enhancement

#188 Loading Icon Between pages
  src/components/student/profile/StudentProfile.js
  src/components/student/projects/ProjectView.js
Labels: enhancement

#189 don't delete my code pls
  src/auth/authActions.js
Labels: bug

#193 Tiny, tiny fix - don't display acclaim for those who haven't provided
  src/components/student/profile/StudentProfile.js
Labels: bug

#202 Logged-in user profile shows projects and doesn't show ghost info from a previous profile
  src/components/student/profile/StudentProfile.js
  yarn.lock
Labels: bug

#216 Make admin routes private, add a logged-in user role prop to each Pri…
  src/config/PrivateRoute.js
  src/config/Routes.js
Labels: bug

#219 Profile edit bug fixed
  src/components/FilterSearch/FilterSearch.js
  src/components/student/profile/DeleteModal.js
  src/components/student/profileqs/profileqsActions.js
  src/components/student/profileqs/profileqsReducer.js
  src/components/student/share/Share.js
Labels: bug
